language: node_js
node_js:
- iojs
- '0.12'
- '0.11'
- '0.10'
deploy:
  provider: npm
  email: leoncoto@gmail.com
  api_key:
    secure: ifxuLbGWfIiuc4gLzyJW/mFFn1EGmpPp0hoeyVTldRSokSy6QU+bxSQY89MZB6mykHYaxLdFPhvGsS/qh6loOkrowEGrKetPH/xIAgmmOCIh6c3f8lVSveCAM16KCvAiQZTWuT7B/vLBZdwST0U0NYdpcx5/bUK43ekx6XyGixn1U+3QHKL64k/bkX/XPoEEI/SH6iE2bX3PDTFbaNty4C5G0PZMBY72E+YtJZ1+uhqp6Xwuvfu24zQ5/nwP7bnXbSgtwFjr3GBjtSo46Yi5Q4x4CJCxBDYdbiWcz1SqhO9tnrsxD4GojSBUpc1zvRtfConCK/SI/hL+76NyEnwaqjYu01mp+yBtnCLgOY3xw1hV2kKHmBa9j11oWGsISozPComJHKFhxcClZWZAF3bqiQeZZCsDNwuh2vMJrwhjsJjgBzbo5GVyFVnduXUwdTlzEBiG34d89cbI+pHwT1xr1dQ/cSytAohKTTsG5r1V8VrmxavCpNwciNMyuAc0N30oGtcldCZ+UXO99ZreZeZydoVXIeSkTbOumo18wK7qhB1WRmIGqsDTsemsQEd+CvGS4opFkRkL+s8w/RrZmv/0gbQi5xLEooB74BWKts1t71BM2KWAq4fRxs1oT06mAmAS/3Rg6hr/LbaU51HHoMQn+UmUBdnQNmNZZo+EfJFu+ZA=
  on:
    tags: true
    repo: elgrancalavera/prufer
